### ISSUE TITLE
Import the genegraph-dev GKE cluster into a terraform

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#138]
Genegraph clusters are currently created and maintained manually. 

**Success criteria** 
Produce a terraform manifest that can run a terraform apply against our current genegraph-dev cluster without suggesting any modifications. 

**Bonus points** 
Provide a reusable module that can do the same for genegraph-dev, but by using parameterized inputs.

**Comment by larrybabb** [comment]
@sjahl i'm not sure if this is a duplicate issue or not. Feel free to comment on this as to when and if you may be able to get to it.

If you are unsure of the nature or origin of this request then I would ask you to reach out to @tnavatar to see if you two can devise a plan for what we are aiming to achieve and if possible if you can assist with executing on that.

Please include @toneillbroad in the plan as well to make sure we are all in sync.

**Comment by sjahl** [comment]
I'm pretty sure the origin of this was as a follow-up from the postmortem. Terraform configs are definitely on my stack of things to work on, though I was planning on starting that up once I made some decisions on app deployment.

A starting point for GKE-in-terraform is in my testing cluster config at https://github.com/broadinstitute/tgg-extsec-testing/blob/main/tf/main.tf. With existing clusters like clingen, we'll want to look into importing them, so that we won't have to do a ground-up redeploy: https://www.terraform.io/docs/cli/import/index.html

@larrybabb Maybe it makes sense for me to hop on the clingen/broad coding session on Thursday? We can touch base on which clusters we have and where code should go, etc.

**Comment by larrybabb** [comment]
@sjahl yes. please join us Thu. i'll add you as a permanent option to the thu invite.

**Comment by sjahl** [comment]
We're going to start here by importing the existing genegraph-dev GKE cluster into a terraform configuration to avoid needing to redeploy from scratch. I'll put the terraform configuration in a subdirectory of the architecture repo.

Success criteria here will be producing a terraform manifest that can run a `terraform apply` against our current genegraph-dev cluster without suggesting any modifications. Bonus points if we can provide a reusable module that can do the same for genegraph-dev, but by using parameterized inputs.
