### ISSUE TITLE
ID term suggester and search capability

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#145]
Originated in Website Jira board [CGWM-235](https://broadinstitute.atlassian.net/browse/CGWM-235) from @plweller3 
---
Update to the genegraph suggester to recognize an ID term and search on it.  For example, if HGNC:64 is entered, we don't want to match the HGNC: part.  Just the numeric.  We just want to recognize that the HGNC: prefix triggers a curie search, not a name search.

**Comment by theferrit32** [comment]
This is something we will want across other search endpoints as well. I created something for this in the clinvar graphql package but we can see if it can be made more robust and pulled out to a common space for use in other resolver packages. We may need to add to `namespaces.edn` if values provided externally through the graphql can reference those names. Or if that isn't suitable we can create a curie namespaces file specifically for prefixes and expanded forms we want to use to resolve curies.

https://github.com/clingen-data-model/genegraph/blob/2b3d9237d95428b3c61f9ac76060d20a088d59cc/src/genegraph/source/graphql/clinvar/common.clj#L27-L35

**Comment by toneillbroad** [comment]
This issue needs clarification before it can be implemented.

== Background On ==

Suggesters are often confused with general text search. They do perform text search but under certain constraints.

Suggesters have a type. We currently have suggesters with type GENE, DISEASE and DRUG. When using a suggester, you always supply the type you want to search against.

Suggesters are used only in the context of a search box dropdown. To phrase that differently, a suggester merely facilitates typeahead while the user types in a search box. With each keystroke the user enters, the suggester of the given type searches its single text field for text that matches what the user typed and returns those matches.

Here is what the data inside the GENE suggester currently looks like for the gene ‘NGLY1’:

{
        "curie": "NCBIGENE:55768",
        "curations": [
          "GENE_DOSAGE",
          "GENE_VALIDITY"
        ],
        "iri": "https://www.ncbi.nlm.nih.gov/gene/55768",
        "text": "NGLY1",
        "type": ":GENE",
        "weight": 0
 }

We are using an AnalyzingInfixSuggester from Lucene, It’s API states “Analyzes the input text and then suggests matches based on prefix matches to any tokens in the indexed text. This also highlights the tokens that match.”

When the GENE suggester is being searched with the users input, the text field in the suggester is being searched matching all characters starting from the beginning of tokens in the text field. So a text search against the GENE suggester with the user input of “GLY1” will NOT MATCH the gene “NGLY1” shown above.

The beauty of the suggester is that when the user does type in “NGLY1” or some portion that matches the text field in the suggester based on the constraints above, the other fields in the suggester - curations, curie, iri, highlighted text (not stored but it is returned by the suggester), etc. - are available to be returned and used by the system.

== Background Off ==

With regard to this ticket, are we looking at trying to use the GENE suggester for this (that’s what I am assuming)? Or do we need a new suggester to support this? What is the user context in which we expect the user to enter the HGNC:?? term?

If it is the gene context, then we would either need to add the HGNC:?? term to the text field (i.e. “NGLY1 HGNC:####”) and see if the suggester matches the HGNC token portion when searching.

Otherwise we would either need a new HGNC suggester and the front end would need to choose the HGNC suggester when searching for HGNC terms.

Or we would need to custom code our own suggester that suits our needs.

**Comment by KelseaChang5** [comment]
December 7th Triage: Rejected Feature
@larrybabb to follow up with Phil

**Comment by larrybabb** [comment]
Phil implemented this in the website. GGraph approach no longer required.
