### ISSUE TITLE
Validate incoming data using SHACL shapes

### ISSUE THREAD

**Issue by tnavatar** [clingen-data-model/genegraph#33]
The import functionality for data coming in over the streaming service should include a step that checks to see whether the incoming data conforms to the expected SHACL shape. If it does not, we may want to report the failure to validate, so that corrective steps can be taken.

**Comment by larrybabb** [comment]
Jira task for Tristan at [CDX-6](https://broadinstitute.atlassian.net/browse/CDX-6?atlOrigin=eyJpIjoiODY1MDIxOWE5ZGZiNGU3MWIzNWMxYTIxNDdmYzg4NTciLCJwIjoiaiJ9)

**Comment by sgoehringer** [comment]
@tnavatar @larrybabb 

**Background** 
Website Actionability stakeholders seek to have all of their curations findable on the website when accessing a gene, condition, or viewing a list of curated genes.  This feature is current available on the website (with issues due to curation bundling).  Those issues are documented in work statement "Correcting Actionability Curation relationships in ClinGen Website Search (current search [v3])" from June 2019: https://docs.google.com/document/d/1y_jXGScj7yuIuTBLWKYM25NBgYIYI9NOVkvwtolEBMo/edit#
To correct these issues it was proposed to implement the genegraph feature.  During this the development time the live website continues to receive ACI updates and curations are displayed (with the known curation bundle issue).

**General Problem Statement**
It is my understanding that genegraph is pulling data from the streaming service and it is having issues with 75 of the 209 curation topics. These issues cause the 75 curation topics not to be added and/or create issues with genegraph and thus curated data isn't available to the website (demo site). Missing these curation topics blocks the ability to have stakeholders properly test the new feature.

**Proposed Solution**
@tnavatar seeks to implement a validation service that ensures the data provided to genegraph conforms to an agreed upon SHACL specification that was provided to the ACI team.  

**Proposed Solution Questions**
@sgoehringer has the following questions regarding the proposed solution
1. Where are you proposing the validation check to occur? Prior to reaching the streaming service, after saving in the streaming service, or during the genegraph consumption process?
2. What specifically happens when the data doesn't conform to the SHACL standard?  Is the ACI team aware and ready? 
3. Will this proposed solution work for the other products that share data to the streaming service and genegraph will use?
@larrybabb please feel free to add additional questions that you brought up during the call such as how to roll back etc.

**Acceptance**
- Genegraph is able to consume all 209 ACI curation topics
- A notification process to inform the sender when data doesn't conform to the agreed standard
- ACI data available to website and issue https://github.com/clingen-data-model/clingen-knowledge/issues/3 is able to continue and/or close

**Comment by tnavatar** [comment]
To address the above
1) Right now I would implement the check as part of the genegraph consumption process. In the medium term it would be preferable to validate after data reaches the streaming service, then to republish to a validated topic. I think this would take longer and would be preferable to do as a separate issue.
2) Genegraph will roll back the update if incoming data does not conform to the expected spec. This event will be written to the log, but no further action will be taken at this time. Planning and executing a notification strategy will be done later as a separate issue.
3) This solution would be intended to work for all data published to the streaming service. The intention will be to have SHACL files for all relevant incoming data.

I would propose removing the notification process as a part of the acceptance criteria unless a delay is acceptable.

**Comment by sgoehringer** [comment]
@tnavatar thanks for the update. I want to be able to assure the AC stakeholders that this proposed solution will ensure all expected curations will show on the site and also continue to show as new/updates to curations roll in. Please advise.
