### ISSUE TITLE
Draft of Genegraph team roadmap for 2022

### ISSUE THREAD

**Issue by tnavatar** [clingen-data-model/genegraph#372]
Build a first draft of product roadmap; will review with team and stakeholders over the course of the following weeks.

[Link to Roadmap](https://docs.google.com/document/d/1eGLhcMCAGXH6IV8Exgos4zeqh6AT7e0RY5GFA68Sq_8/edit) draft/high level points from meeting on January 14, 2022

**Comment by KelseaChang5** [comment]
@tnavatar Can you please attach your roadmap draft that you have so far? Thanks!

**Comment by larrybabb** [comment]
Tristan added his roadmap notes to the end of the Roadmap doc linked in the description above.

**Comment by KelseaChang5** [comment]
**Feedback from roadmap presentation on Feb 4th, 2022:**

- Heidi, Christa, and Erin all expressed that they would like a more concrete/firm timeline on when certain projects are expected for completion for more transparency on when to expect certain projects to move forward. 
- Heidi also wanted more details on what each of the blocks are on the Roadmap Delivery Timeline, so that she understands who needs each of these deliverables and when do they need it by, so that it's easier to get a sense of what to prioritize 
- Erin expressed that she sometimes feels frustrated that ClinGen always has a bunch of little things left hanging/unfinished while other projects are also being pursued, and so she would appreciate if some things for ClinGen were seen through to completion at a slightly higher priority 
- Phil expressed that he has a lot of questions that he would like to ask on a future Broad/Geisinger Data Platform Sync Up
