### ISSUE TITLE
Gene Curation Feedback Response 

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/genegraph#386]
### Gene Curation Feedback 
[Link to Gene Curation Review sheet](https://docs.google.com/spreadsheets/d/1X_VIKoRWLQRGhx6brxbqap29uy89kCAX/edit#gid=159230927)

**For _RGS9_** ([link to gene page](https://genegraph-validity-test.clingen.app/#/resource/CGGV%3Af90aa6cd-9e08-4fab-b6c3-570beb8232dd))
1. Can't see evidence summary
2. I also don't see the "total" scores (total genetic evidence, total experimental evidence, overall total) - we will definitely want to display this on the website and be able to query by this information, so I don't know if you need to pull it in or if it should be calculated by the website based on what you have here.
3. For the compound het case, Michaelides Proband 3: how will the website "know" which two of these variant entries go together in order to display them together and tally their score? 
4. Need to display "explanation" field for Experimental evidence.
5. This entry has two separate model systems entries, each with the same label and score, but they should be coming from two different papers (Kuburas and Chen).  GeneGraph is showing the Kuburas entry twice.

Completed when we let Erin know of responses to these prompts.

**Comment by tnavatar** [comment]
* Can't see evidence summary
* I also don't see the "total" scores (total genetic evidence, total experimental evidence, overall total) - we will definitely want to display this on the website and be able to query by this information, so I don't know if you need to pull it in or if it should be calculated by the website based on what you have here.

These both appear to be present and plain to me based on the existing UI. Maybe Erin is looking for something different than I expect.

* For the compound het case, Michaelides Proband 3: how will the website "know" which two of these variant entries go together in order to display them together and tally their score?

Good point; These may not be explicitly connected currently. I can make sure this gets done.

* Need to display "explanation" field for Experimental evidence.

This mostly looks like a bug I introduced when tidying up the UI. Should be an easy fix.

That said, I'm not seing explanations for the Gene Expression evidence. Let me dig into that and find out why.

* This entry has two separate model systems entries, each with the same label and score, but they should be coming from two different papers (Kuburas and Chen). GeneGraph is showing the Kuburas entry twice.

This is a good catch; will investigate the cause of this

**Comment by KelseaChang5** [comment]
Emailed Erin and also put these responses in the GC sheet. Closing this ticket
