### ISSUE TITLE
PMIDs not always being mapped properly

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#531]
Phil says: 

Regarding the AASS issue - two of the tree evidence records are passing a source: null instead of the PMID information.  A quick check of the GCI  shows that all the records do have PMIDs, so that seem to imply something didn’t get mapped correctly in genegraph?

You can see eveidence of this by going to:
https://devsearch.clingen.info/
and pulling up the AASS gene - you will see an error if this is broken

**Comment by tnavatar** [comment]
One observation while looking into this, some proband scores aren't carrying over because the field denovo is required, though this doesn't seem to be the specific issue experienced in this case, it's still a problem.

Completing the work I'd started on testing migration outcomes should help identify issues like this when they arise.
