### ISSUE TITLE
Research Classification label issue in gene validity list results

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#704]
From 11/2/2022 Phil slacked:
 I traced a failure to a weird change in the gene_validity_assertions() call for gvdev.  For the returned curation list, the classification label in gvdev for the disputed items is now “disputed”.  In the production, it is “disputing”.   Is this an error or a permanent change?

In our meeting yesterday, I believe Tristan said he would look into this.

**Comment by tnavatar** [comment]
I made a mistake in the original version; the SEPIO term selected was 'disputing' from base-SEPIO, rather than 'disputed' from the Gene Validity Extensions. The two reasonably mean different things, and the latter should have been selected.

That said, Phil is keying off the label and not the term identifier, and it's easy enough for now to change the label to 'disputing' to make his life a little bit easier. Resolved without requiring code commit.
